### ISSUE TITLE
How about a screenshot in your readme?  Show off what you made since very few people make a GUI ❤

### ISSUE THREAD

**Issue by PySimpleGUI** [ignorance-uwu/Python-stuffy#2]
![image](https://user-images.githubusercontent.com/46163555/225038183-b7d07d4b-46bd-412e-be08-42c9f3841da7.png)

You can paste a screenshot into a GitHub issue, and then use that image in your readme.  If you were to take the code generated for the above image:
`![image](https://user-images.githubusercontent.com/46163555/225038183-b7d07d4b-46bd-412e-be08-42c9f3841da7.png)`

and paste it into your readme.md, then you will get an image embedded into your readme.  People will love it!

I love what ya made!  ![image](https://user-images.githubusercontent.com/46163555/225038599-8d03fe11-e89f-43d7-9029-ed38cb781285.png)

Note... I removed the hard-coded size since PySimpleGUI will size the window for you.

This leads me to the Reddit Post...

--------------------------------

## Questions about your post...

![image](https://user-images.githubusercontent.com/46163555/225038883-205deac4-26b8-4e76-9522-8dbb0a393f01.png)

I was wondering about the crossed-out sections of your post on Reddit.  They semed like 2 of the most important parts of the entire post.

I'm curious if it stopped being fun for some reason.

**Comment by milkyicedtea** [comment]
Hey, thanks for reaching out!
I like the idea you suggested, and I will put a screenshot showing the whole GUI in the next commit. (Working on it at the moment!)
About the Reddit post:
For both questions the answer is that I don't think those sections are important to understand what the project does or how it's made, they were just something I wanted to add regarding how I personally felt and still feel about the project.
***BUT***
- Yes! It turned out to be really fun! This was my first time experiencing with the making of a GUI of any kind, and even though I'm unsure about the design, I'm still really happy of how it turned out (even just that it was working!)
- And yes, I'm still very proud of it! I remember showing it to my friends and family (especially my dad, since he's a programmer too!) way before posting it online, and being very explanatory about how the program worked and the struggles I had making it. I will continue being proud of this for the longest time, first experiences last forever :)

Lastly, thanks again for the kind comment, it really means a lot knowing how much time I put into this.
I will shortly update the [other issue](https://github.com/milkyicedtea/Random-password-generator/issues/3) :)
